formats:
  meta.date: '%Y-%m-%d'
groups:
  - name: posts
    template: post.html
    rss: true
    path_config:
      - "\"p\""
      - "['meta']['date'].year"
      - "['meta']['handle']"
  - name: generic
    template: generic.html
    rss: false
    path_config:
      - "['meta']['canonical-uri']"
  - name: blog
    template: blog.html
    rss: false
    path_config:
      - "['meta']['canonical-uri']"